### PR TITLE
add a game separator before the game starting message to divide previ…

### PR DESCRIPTION
**Pull request by cai-jack**
…ous game messages better

### CODE REVIEW

**Comment by rbtying** [comment]
Do you mind adding a screenshot ?

**Comment by cai-jack** [comment]
Screen Shot 2020-06-29 at 4 10 09 PM

**Comment by cai-jack** [comment]
Screen Shot 2020-06-29 at 4 12 00 PM

**Comment by cai-jack** [comment]
Screen Shot 2020-06-29 at 4 19 38 PM
this one shows better

**Comment by rbtying** [comment]
awesome, thank you!

**Pull request merged**
