### PR TITLE
bug fix: eliminate flicker during drawing by using synced file loadin…

### PR DESCRIPTION
**Pull request by cai-jack**
…g instead of async

the use of suspense and lazy loading of svg cards causes annoying flickering especially at draw phase. This fix should make it  visually more pleasant to use

### CODE REVIEW

**Comment by cai-jack** [comment]
hmm, ci failed complaining about something I did not change. local cargo clippy runs  fine:

    Checking shengji-core v0.1.0 (/Users/rust/Projects/shengji/core)
    Checking shengji v0.1.0 (/Users/rust/Projects/shengji/backend)
    Finished dev [unoptimized + debuginfo] target(s) in 8.97s

**Comment by cai-jack** [comment]
error: couldn't read backend/src/../../frontend/dist/playing-cards.js: No such file or directory (os error 2)
##[error]   --> backend/src/main.rs:688:25
    |
688 | static CARDS_JS: &str = include_str!("../../frontend/dist/playing-cards.js");
    |                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

looks like ci does not pull this file?

**Comment by cai-jack** [comment]
@rbtying

**Comment by cai-jack** [comment]
yes. it is consistently flickering during the draw phase, even after resetting the game with cards already loaded, not very usable in my opinion. Also, the svg files are already loaded into client side with the static imports, should not consume extra bandwidth afterwards.

**Comment by rbtying** [comment]
> yes. it is consistently flickering during the draw phase, even after resetting the game with cards already loaded, not very usable in my opinion.
Interesting. we could try bundling all of the SVGs together into a single async loaded component?

> Also, the svg files are already loaded into client side with the static imports, should not consume extra bandwidth afterwards.
Since 90% of players will never use the SVG cards, and the JS bundle without the SVG is ~350KiB (and with SVG is ~1.4MiB), I'd prefer not to slow down load time for all players unless they have actually opted into using SVG cards. I can't reproduce the issue you're seeing -- what browser are you using? Do you see more than one request to playing-cards.js?

**Comment by cai-jack** [comment]
Google Chrome on MacOS. I ran a few more tests: If a subsequent game draws cards that were not in previous game(s), the most noticeable flickering occurs when a "new" card is drawn and inserted into the middle of the hand. It feels like the cards after the insertion point jumped for the insertion:). I don't think it is the issue of more request to playing-cards.js, the async loading is. If your concern is the bandwidth, is there a way to conditionally load them and make the cards available only when the setting is on? react.lazy seems to make sure you can't do that until the component is ready to render

**Comment by rbtying** [comment]
Interesting. Like I said, I can't reproduce -- I tried with Chrome on Catalina. The intent of the `React.lazy` here was to async load all of the cards once any card was requested. If we're for some reason observing transient states while loading new cards, even after the network request, we can try bundling all of the cards into a single component to async load (rather than loading them one at a time, even though the underlying file is the same file). If you're familiar with another way to do this, I'm happy to try it?

I'm strongly against adding ~3 seconds of load time (@ 300KiB/s download rate) for a feature that very few people seem to use.

**Comment by rbtying** [comment]
https://github.com/rbtying/shengji/tree/svg-card-batch-load

Does this resolve the issue locally for you ?

**Comment by cai-jack** [comment]
Yes. it does! Thanks.

**Pull request closed without merging**
