### PR TITLE
#35, disallow picking trump cards as friend

### PR DESCRIPTION
**Pull request by cai-jack**
I only tested with actual running cases for both trump and no trump, not sure if there are any integrated test cases required.

### CODE REVIEW

**Comment by cai-jack** [comment]
There are a few lint errors that are not related. Please let me know how you plan to proceed with them. Here are the snippet of the errors:

error: redundant closure found
##[error]   --> core/src/game_state.rs:531:37
    |
531 |                     .unwrap_or_else(|| vec![])
    |                                     ^^^^^^^^^
    |
note: the lint level is defined here
   --> core/src/lib.rs:1:9
    |
1   | #![deny(warnings)]
    |         ^^^^^^^^
    = note: `#[deny(clippy::redundant_closure)]` implied by `#[deny(warnings)]`
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#redundant_closure

error: using `clone` on a `Copy` type
##[error]   --> core/src/interactive.rs:126:37
    |
 Check Rust formatting...

**Comment by rbtying** [comment]
@cai-jack what version of rustc are you using?

**Comment by cai-jack** [comment]
rustc 1.43.1 (8d69840ab 2020-05-04) @rbtying

**Comment by cai-jack** [comment]
but the lint failed at github's ci test, not my local env @rbtying

**Comment by rbtying** [comment]
I went ahead and fixed that in master! clippy got more strict on stable, I suppose.

For the actual diff -- do you mind also updating the server code to check?

https://github.com/rbtying/shengji/blob/d126f0b8b5e8dc31ec966ec641f0edcecb3f0834/core/src/game_state.rs#L1072

**Comment by cai-jack** [comment]
server side check is added. ci build seems to pass @rbtying

**Comment by cai-jack** [comment]
I retested the playing scenarios as well, both passed

**Comment by rbtying** [comment]
thank you!

**Pull request merged**
