### PR TITLE
added functionality to bid with same number of cards but higher suit

### PR DESCRIPTION
**Pull request by kjzhang**
for example, S2 S2 can be bid over H2 H2

### CODE REVIEW

**Review by rbtying — CHANGES_REQUESTED** [review]
Hi @kjzhang , thanks for making this change :) I'd be happy to merge it.

Two things:

1. do you mind adding a test for this functionality, so it doesn't get broken? There are other bidding tests at the end of this file.
2. do you mind updating the changelog? it's in frontend/src/Credits.tsx

**Comment by kjzhang** [comment]
I pushed the changes. I haven't used pull requests here before so let me know if I have to do anything else.

**Review by rbtying — APPROVED** [review]
thank you! I'll go ahead and merge this. The code is generally deployed early in the morning, so hopefully you'll be able to play with this tomorrow night :)

**Comment by kjzhang** [comment]
does the lint error need to be fixed?

**Comment by rbtying** [comment]
> does the lint error need to be fixed?

I gotchu

**Pull request merged**
